server:
  port: 8080


spring:
  application:
    name: IntegratedDesign
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?useSSL=false&serverTimezone=UTC
    username: root
    password:
  web:
    resources:
      static-locations: classpath:/static/


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

